services:
  - docker
env:
  global:
    # Do not prompt for user input when using any SDK methods.
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - WEB_GIT_SHA=$(git rev-parse HEAD:./web)
    - API_GIT_SHA=$(git rev-parse HEAD:./api)
    - WORKER_GIT_SHA=$(git rev-parse HEAD:./worker)
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv -in client-secret.json.enc -out client-secret.json -d
  # The Google Cloud SDK on Travis is pretty old (2014). So if
  # you want to use an up-to-date version, you have to install
  # your own. This config is the bare minimum you'll need to
  # get an updated version of the SDK + kubectl.
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud version
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud config set project k8s-fibonacci-app
  - gcloud config set compute/zone europe-central2-a
  - gcloud container clusters get-credentials fibonacci-app-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t fibonacci-app-web-dev -f ./web/Dockerfile.dev ./web

script:
  - docker run -e CI=true fibonacci-app-web-dev npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
