apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emirhanaydin-com-tls
spec:
  secretName: emirhanaydin-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: emirhanaydin.com
  dnsNames:
    - emirhanaydin.com
    - www.emirhanaydin.com
