apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emirhanaydin-com
  namespace: default
spec:
  secretName: emirhanaydin-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: emirhanaydin.com
  dnsNames:
    - emirhanaydin.com
    - www.emirhanaydin.com
